# ./docker-compose.yml

version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '80:80'
    container_name: nfun-login
    command: npm start
    restart: always
  mysql:
    image: mysql
    restart: always
    container_name: mysql
    environment:
      - MYSQL_DATABASE=nfun
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=153153
      - TZ=Asia/Seoul
    # volumes:
    #   - ./db:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    ports:
      - 3306:3306
