# ./docker-compose.yml

version: '3'

services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    container_name: nfun-login
    command: npm start
    restart: always
  mysql:
    image: mysql
    restart: always
    container_name: mysql
    environment:
      - MYSQL_DATABASE=nfun
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=153153
      - TZ=Asia/Seoul
    volumes:
      - ./db:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
